=== msredhotero/360futbolnuevo/archivos/pesado/LstJugadores1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="LstJugadores1" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="LstJugadores1">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="id" index-key="id " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Id1" index-key="Id1 " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACPbhCifeF2RI5ZGwqTM5HUAAAAAEGpqIX5jORAbSR5Z+C10wJMAHMA
dABKAHUAZwBhAGQAbwByAGUAcwAxAAAAAAAAANFgiCUCHQ9Mn13FWkTjI1IHAAAA
j24Qon3hdkSOWRsKkzOR1EkAZAAxAAAAAAAAAHwIPGH5ZCVPlLdVXW1FyiUHAAAA
j24Qon3hdkSOWRsKkzOR1E4AbwBtAGIAcgBlAEUAcQB1AGkAcABvAAAAAAAAANDW
y05OsYVJiCS3QGVnEpMHAAAAj24Qon3hdkSOWRsKkzOR1GMAYQBwAGkAdABhAG4A
AAAAAAAACVFOf09v6kC8yFF2qpEbGwcAAACPbhCifeF2RI5ZGwqTM5HUYwBhAHAA
aQB0AGEAbgB0AGUAbABlAGYAbwBuAG8AAAAAAAAAThOx2PNPF0ymdl4IVNcofQcA
AACPbhCifeF2RI5ZGwqTM5HUYwBhAHAAaQB0AGEAbgBlAG0AYQBpAGwAAAAAAAAA
FucPhCUpckanIPW8pvBOtAcAAACPbhCifeF2RI5ZGwqTM5HUYwBhAHAAaQB0AGEA
bgBmAGEAYwBlAGIAbwBvAGsAAAAAAAAAFc8CUwuh+kOC1Q5VhrUwWgcAAACPbhCi
feF2RI5ZGwqTM5HUcwB1AGIAYwBhAHAAaQB0AGEAbgAAAAAAAAAYq+7ttd80R6ES
ax8KRuVLBwAAAI9uEKJ94XZEjlkbCpMzkdRzAHUAYgBjAGEAcABpAHQAYQBuAHQA
ZQBsAGUAZgBvAG4AbwAAAAAAAAB1yII50VQJTICDocy2ypdsBwAAAI9uEKJ94XZE
jlkbCpMzkdRzAHUAYgBjAGEAcABpAHQAYQBuAGUAbQBhAGkAbAAAAAAAAADpRHcm
BzFLR6pbBU2bwEMKBwAAAI9uEKJ94XZEjlkbCpMzkdRzAHUAYgBjAGEAcABpAHQA
YQBuAGYAYQBjAGUAYgBvAG8AawAAAAAAAAD/j8epHtzVSZo335BZbE5jBwAAAI9u
EKJ94XZEjlkbCpMzkdRpAGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAEAAAA
AAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="j24Qon3hdkSOWRsKkzOR1A==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Id1" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="NombreEquipo" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3345"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="capitan" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2400"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="capitantelefono" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="capitanemail" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="capitanfacebook" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="subcapitan" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="subcapitantelefono" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="subcapitanemail" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="subcapitanfacebook" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="id" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== msredhotero/360futbolnuevo/archivos/pesado/LstJugadores1.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="LstJugadores1.xsd" generated="2015-03-24T19:27:54">
<LstJugadores1>
<Id1>1</Id1>
<NombreEquipo>4 DE COPA</NombreEquipo>
<capitan>FRANCO VIVA</capitan>
<capitantelefono>3388-466335</capitantelefono>
<capitanemail>FRANCO.VIVA@HOTMAIL.ES</capitanemail>
<capitanfacebook>FRANCOVIVA32</capitanfacebook>
<subcapitan>FRANCO CHAVES</subcapitan>
<subcapitantelefono>221-435-0603</subcapitantelefono>
<subcapitanemail>KAKO.CHAVES@GMAIL.COM</subcapitanemail>
<subcapitanfacebook>FRANCOECHAVES</subcapitanfacebook>
<id>1</id>
</LstJugadores1>
<LstJugadores1>
<Id1>2</Id1>
<NombreEquipo>A CONFIRMAR</NombreEquipo>
<capitan>MAXIMILIANO PINEIRO</capitan>
<capitantelefono>221-643-8003</capitantelefono>
<subcapitan>LEONARDO ROSSER</subcapitan>
<subcapitantelefono>221-350-0125</subcapitantelefono>
<id>2</id>
</LstJugadores1>
<LstJugadores1>
<Id1>3</Id1>
<NombreEquipo>ATLETICO 78</NombreEquipo>
<capitan>ABEL MORALES</capitan>
<capitantelefono>221-5980883</capitantelefono>
<subcapitan>JHON MORALES</subcapitan>
<subcapitantelefono>221-5475531</subcapitantelefono>
<id>3</id>
</LstJugadores1>
<LstJugadores1>
<Id1>4</Id1>
<NombreEquipo>AYACUCHO</NombreEquipo>
<capitan>CERESA EMILIANO</capitan>
<capitantelefono>221-6265286</capitantelefono>
<capitanemail>emilianoceresa@hotmail.com</capitanemail>
<capitanfacebook>Emiliano Ceresa</capitanfacebook>
<subcapitan>ACOSTA MATIAS</subcapitan>
<subcapitantelefono>221-5428776</subcapitantelefono>
<subcapitanemail>matias_aya@hotmail.com</subcapitanemail>
<subcapitanfacebook>Matias Matias</subcapitanfacebook>
<id>4</id>
</LstJugadores1>
<LstJugadores1>
<Id1>5</Id1>
<NombreEquipo>BARRIO HIPODROMO</NombreEquipo>
<capitan>NICOLAS BERNAZA</capitan>
<capitantelefono>221-5079601</capitantelefono>
<subcapitan>AGÜERO GEREMIAS</subcapitan>
<subcapitantelefono>221-5765546</subcapitantelefono>
<id>5</id>
</LstJugadores1>
<LstJugadores1>
<Id1>6</Id1>
<NombreEquipo>CUALQUIER COSA FC</NombreEquipo>
<capitan>Ezequiel Mendoza</capitan>
<capitantelefono>221-596-8365</capitantelefono>
<capitanemail>eduardoezequielmendoza@hotmail.com</capitanemail>
<id>6</id>
</LstJugadores1>
<LstJugadores1>
<Id1>7</Id1>
<NombreEquipo>DE RABONA</NombreEquipo>
<capitan>Sergio Omar Criado</capitan>
<capitantelefono>221-4200053</capitantelefono>
<capitanemail>sercriado85@gmail.com</capitanemail>
<subcapitan>Ivan Sibilio</subcapitan>
<subcapitantelefono>221-6681696</subcapitantelefono>
<subcapitanemail>ivandariosibilio07@gmail.com</subcapitanemail>
<subcapitanfacebook>Ivan Sibilio</subcapitanfacebook>
<id>7</id>
</LstJugadores1>
<LstJugadores1>
<Id1>8</Id1>
<NombreEquipo>DEPORTIVO INTENCION</NombreEquipo>
<capitan>Taulo José Ricardo</capitan>
<capitantelefono>221-5935872</capitantelefono>
<id>8</id>
</LstJugadores1>
<LstJugadores1>
<Id1>9</Id1>
<NombreEquipo>DREAM TEAM</NombreEquipo>
<capitan>Marin Emiliano </capitan>
<capitantelefono>221-438-3494</capitantelefono>
<subcapitan>Victor Silvestre</subcapitan>
<subcapitantelefono>221-563-7768 </subcapitantelefono>
<id>9</id>
</LstJugadores1>
<LstJugadores1>
<Id1>10</Id1>
<NombreEquipo>EL AREA BLANCA</NombreEquipo>
<capitan>JUAN MANUEL FIOL</capitan>
<capitantelefono>221-5610159</capitantelefono>
<subcapitan>MONZOL ABEL</subcapitan>
<subcapitantelefono>221-5453121</subcapitantelefono>
<id>10</id>
</LstJugadores1>
<LstJugadores1>
<Id1>11</Id1>
<NombreEquipo>EL CARMEN</NombreEquipo>
<capitan>Cesar Taborda</capitan>
<capitantelefono>221-632-2387</capitantelefono>
<id>11</id>
</LstJugadores1>
<LstJugadores1>
<Id1>12</Id1>
<NombreEquipo>EL EBOLA</NombreEquipo>
<capitan>RODRIGO ARIEL CABRERA</capitan>
<capitantelefono>221-5406699</capitantelefono>
<subcapitan>Facundo Palacios</subcapitan>
<subcapitantelefono>2945-531423</subcapitantelefono>
<id>12</id>
</LstJugadores1>
<LstJugadores1>
<Id1>13</Id1>
<NombreEquipo>EL MATADOR</NombreEquipo>
<capitan>EMILIO MARTINEZ</capitan>
<capitantelefono>221-5862006</capitantelefono>
<subcapitan>PABLO LLONTOP</subcapitan>
<subcapitantelefono>221-4092206</subcapitantelefono>
<id>13</id>
</LstJugadores1>
<LstJugadores1>
<Id1>14</Id1>
<NombreEquipo>FAUSTO PAPETTI</NombreEquipo>
<capitan>Ruben Barreto</capitan>
<capitantelefono>221-6387171</capitantelefono>
<subcapitan>Enrique Paez</subcapitan>
<subcapitantelefono>221-4772292</subcapitantelefono>
<id>14</id>
</LstJugadores1>
<LstJugadores1>
<Id1>15</Id1>
<NombreEquipo>GUARDA LA JARRA QUE VIENE LUIS</NombreEquipo>
<capitan>Luis</capitan>
<capitantelefono>221-4314774</capitantelefono>
<subcapitan>Hugo</subcapitan>
<subcapitantelefono>221-4558843</subcapitantelefono>
<id>15</id>
</LstJugadores1>
<LstJugadores1>
<Id1>16</Id1>
<NombreEquipo>LA 15 FC</NombreEquipo>
<capitan>DARIO GARCIA</capitan>
<capitantelefono>221-4956409</capitantelefono>
<subcapitan>MAXIMILIANO GARCIA</subcapitan>
<subcapitantelefono>4732664</subcapitantelefono>
<subcapitanemail>221-5749444</subcapitanemail>
<id>16</id>
</LstJugadores1>
<LstJugadores1>
<Id1>17</Id1>
<NombreEquipo>LA 85</NombreEquipo>
<capitan>Roldán Fabián</capitan>
<capitantelefono>221-5916539</capitantelefono>
<subcapitan>Matías Misseri</subcapitan>
<subcapitantelefono>221-5952025</subcapitantelefono>
<id>17</id>
</LstJugadores1>
<LstJugadores1>
<Id1>18</Id1>
<NombreEquipo>LA ACADEMIA</NombreEquipo>
<capitan>LUCAS ZAPATA</capitan>
<capitantelefono>011-53141330</capitantelefono>
<subcapitan>SEBASTIAN ZAPATA</subcapitan>
<subcapitantelefono>221-6497295</subcapitantelefono>
<id>18</id>
</LstJugadores1>
<LstJugadores1>
<Id1>19</Id1>
<NombreEquipo>LA RAMBLA FC</NombreEquipo>
<capitan>Jonatan Calderón </capitan>
<capitantelefono>221-494-8319</capitantelefono>
<capitanemail>El_jone.ve@hotmail.com</capitanemail>
<capitanfacebook>Jc Calderón</capitanfacebook>
<subcapitan>Franco Senta</subcapitan>
<subcapitantelefono>221-670-6311</subcapitantelefono>
<subcapitanemail>Franco_megusta@hotmail.com</subcapitanemail>
<subcapitanfacebook>Franco Martín</subcapitanfacebook>
<id>19</id>
</LstJugadores1>
<LstJugadores1>
<Id1>20</Id1>
<NombreEquipo>LOS AMIGOS DE MESSI</NombreEquipo>
<capitan>Kevin Einschlag</capitan>
<capitantelefono>221-632-1307</capitantelefono>
<capitanemail>kevinela12@hotmail.com</capitanemail>
<capitanfacebook>einschlag kevin</capitanfacebook>
<subcapitan>Felipe Moreno</subcapitan>
<subcapitantelefono>221-655-3110</subcapitantelefono>
<subcapitanfacebook>felipe moreno </subcapitanfacebook>
<id>20</id>
</LstJugadores1>
<LstJugadores1>
<Id1>21</Id1>
<NombreEquipo>LOS BORBOTONES</NombreEquipo>
<capitan>MARIANO RIVERO</capitan>
<capitantelefono>221-6372352</capitantelefono>
<subcapitan>LUCAS VALDEMOROS</subcapitan>
<subcapitantelefono>221-5755162</subcapitantelefono>
<id>21</id>
</LstJugadores1>
<LstJugadores1>
<Id1>22</Id1>
<NombreEquipo>LOS PERROS CHAKALES FC</NombreEquipo>
<capitan>Eber Nicolas Moyano</capitan>
<capitantelefono>221-6402601</capitantelefono>
<subcapitan>Laureano Moreno</subcapitan>
<subcapitantelefono>221-5373063</subcapitantelefono>
<id>22</id>
</LstJugadores1>
<LstJugadores1>
<Id1>23</Id1>
<NombreEquipo>LOS PINIPONES</NombreEquipo>
<capitan>LOPEZ ENZO</capitan>
<capitantelefono>221-4194252</capitantelefono>
<capitanfacebook>ENZO NAHUEL LOPEZ</capitanfacebook>
<subcapitan>LOPEZ HECTOR</subcapitan>
<subcapitantelefono>221-6186468</subcapitantelefono>
<subcapitanfacebook>HECTOR LOPEZ</subcapitanfacebook>
<id>23</id>
</LstJugadores1>
<LstJugadores1>
<Id1>24</Id1>
<NombreEquipo>LOS RANCIOS</NombreEquipo>
<capitan>Matias Morales </capitan>
<capitantelefono>221-476-8745</capitantelefono>
<subcapitan>Jose Vazquez </subcapitan>
<subcapitantelefono>221-569-4314</subcapitantelefono>
<id>24</id>
</LstJugadores1>
<LstJugadores1>
<Id1>25</Id1>
<NombreEquipo>LOS RUSTICOS</NombreEquipo>
<capitan>Marcos Ricci</capitan>
<capitantelefono>11-663-65492 </capitantelefono>
<id>25</id>
</LstJugadores1>
<LstJugadores1>
<Id1>26</Id1>
<NombreEquipo>MACHETE FC</NombreEquipo>
<capitan>Dimitri Ivaskevich</capitan>
<capitantelefono>221-610-4168</capitantelefono>
<capitanemail>ariel9_@hotmail.com</capitanemail>
<capitanfacebook>Dimitri Ivaskevich</capitanfacebook>
<subcapitan>Martin Zotti</subcapitan>
<subcapitantelefono>0221-498-7653</subcapitantelefono>
<subcapitanemail>martinzotti@hotmail.com</subcapitanemail>
<subcapitanfacebook>Martin Zotti</subcapitanfacebook>
<id>26</id>
</LstJugadores1>
<LstJugadores1>
<Id1>27</Id1>
<NombreEquipo>MAS O MENOS</NombreEquipo>
<capitan>MARITO HERRERA</capitan>
<capitantelefono>2216225231</capitantelefono>
<capitanemail>FELI_LA12_1@HOTMAIL.COM</capitanemail>
<capitanfacebook>MARITO HERRERA</capitanfacebook>
<subcapitan>MATIAS TERREIN</subcapitan>
<subcapitantelefono>2215944405</subcapitantelefono>
<subcapitanemail>TERREIN.MATIAS@YAHOO.COM</subcapitanemail>
<subcapitanfacebook>MATIAS TERREIN</subcapitanfacebook>
<id>27</id>
</LstJugadores1>
<LstJugadores1>
<Id1>28</Id1>
<NombreEquipo>MONASTERIO FC</NombreEquipo>
<capitan>Matias Rodriguez</capitan>
<capitantelefono>221-355-5670</capitantelefono>
<capitanemail>4527121</capitanemail>
<subcapitan>Juan Rodriguez</subcapitan>
<subcapitantelefono>221-498-7475</subcapitantelefono>
<subcapitanemail>4573510</subcapitanemail>
<id>28</id>
</LstJugadores1>
<LstJugadores1>
<Id1>29</Id1>
<NombreEquipo>MUCHO FC</NombreEquipo>
<capitan>Lugli Franco</capitan>
<capitantelefono>221 3166590</capitantelefono>
<capitanemail>franlugli@gmail.com</capitanemail>
<capitanfacebook>Fran Lugli</capitanfacebook>
<subcapitan>Urrutipi, Ariel</subcapitan>
<subcapitantelefono>221 5938456</subcapitantelefono>
<subcapitanemail>arielurrutipi@gmail.com</subcapitanemail>
